import type { TipoBloco } from '../types'

export interface EditalMateria {
  nome: string
  tipo: TipoBloco
  prioridade: 'alta' | 'media' | 'baixa'
  conteudos: string[]
}

export interface EditalCatalogItem {
  id: string
  nome: string
  materias: EditalMateria[]
}

export const EDITAIS_PREDEFINIDOS: EditalCatalogItem[] = [
  {
    id: 'pcdf',
    nome: 'Polícia Civil do Distrito Federal',
    materias: [
      {
        nome: 'Língua Portuguesa',
        tipo: 'base',
        prioridade: 'alta',
        conteudos: [
          'Interpretação e compreensão de textos',
          'Tipos e gêneros textuais',
          'Ortografia oficial',
          'Semântica e significação das palavras',
          'Coesão e coerência textual',
          'Conectores e elementos de referenciação',
          'Classes de palavras',
          'Verbos: tempos, modos e correlação verbal',
          'Sintaxe do período simples',
          'Sintaxe do período composto',
          'Coordenação e subordinação',
          'Pontuação',
          'Concordância verbal e nominal',
          'Regência verbal e nominal',
          'Crase',
          'Colocação pronominal',
          'Reescrita de frases e parágrafos',
        ],
      },
      {
        nome: 'Língua Inglesa',
        tipo: 'base',
        prioridade: 'media',
        conteudos: [
          'Compreensão de textos em inglês',
          'Vocabulário pelo contexto',
          'Falsos cognatos',
          'Conectores',
          'Gramática aplicada à interpretação',
        ],
      },
      {
        nome: 'Conhecimentos sobre o Distrito Federal',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'História do Distrito Federal',
          'Geografia do Distrito Federal',
          'Realidade social e étnica do DF',
          'Cultura do DF',
          'Política e economia do DF',
          'Região Integrada de Desenvolvimento do DF e Entorno — RIDE',
          'Lei Complementar nº 94/1998',
        ],
      },
      {
        nome: 'Legislação PCDF',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Lei nº 8.112/1990',
          'Lei nº 4.878/1965',
          'Decreto-Lei nº 2.266/1985',
          'Lei nº 9.264/1996',
          'Decreto nº 30.490/2009',
          'Lei Orgânica do Distrito Federal',
          'Polícia Civil na LODF',
          'Lei nº 13.869/2019 — Abuso de Autoridade',
          'Lei nº 8.429/1992 — Improbidade Administrativa',
        ],
      },
      {
        nome: 'Matemática e Raciocínio Lógico',
        tipo: 'base',
        prioridade: 'alta',
        conteudos: [
          'Razões e proporções',
          'Regra de três simples',
          'Porcentagem',
          'Equações de 1º e 2º graus',
          'Sequências numéricas',
          'Progressões aritméticas e geométricas',
          'Funções e gráficos',
          'Princípios de contagem',
          'Probabilidade',
          'Operações com conjuntos',
          'Estruturas lógicas',
          'Lógica de argumentação',
          'Lógica proposicional',
          'Tabelas-verdade',
          'Equivalências lógicas',
          'Leis de De Morgan',
          'Diagramas lógicos',
          'Lógica de primeira ordem',
          'Problemas aritméticos, geométricos e matriciais',
        ],
      },
      {
        nome: 'Atualidades — Discursiva',
        tipo: 'rot',
        prioridade: 'baixa',
        conteudos: [
          'Segurança pública',
          'Transportes',
          'Política',
          'Economia',
          'Sociedade',
          'Educação',
          'Saúde',
          'Cultura',
          'Tecnologia',
          'Energia',
          'Relações internacionais',
          'Desenvolvimento sustentável',
          'Ecologia',
          'Inter-relações históricas dos temas atuais',
        ],
      },
      {
        nome: 'Direito Administrativo',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Organização administrativa',
          'Centralização e descentralização',
          'Concentração e desconcentração',
          'Administração direta e indireta',
          'Autarquias, fundações, empresas públicas e sociedades de economia mista',
          'Atos administrativos',
          'Agentes públicos',
          'Poderes administrativos',
          'Uso e abuso de poder',
          'Licitações',
          'Contratação direta, dispensa e inexigibilidade',
          'Controle da administração pública',
          'Responsabilidade civil do Estado',
        ],
      },
      {
        nome: 'Direito Constitucional',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Constituição Federal de 1988',
          'Direitos e garantias fundamentais',
          'Segurança Pública na Constituição Federal',
          'Título V, Capítulo III — Da Segurança Pública',
        ],
      },
      {
        nome: 'Direito Penal',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Aplicação da lei penal',
          'Princípios penais',
          'Lei penal no tempo e no espaço',
          'Tempo e lugar do crime',
          'Lei penal excepcional, especial e temporária',
          'Contagem de prazo',
          'Irretroatividade da lei penal',
          'Crimes contra a pessoa',
          'Crimes contra o patrimônio',
          'Crimes contra a administração pública',
          'Disposições constitucionais aplicáveis ao Direito Penal',
        ],
      },
      {
        nome: 'Direito Processual Penal',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Disposições preliminares do CPP',
          'Inquérito policial',
          'Notitia criminis e delatio criminis',
          'Indiciamento',
          'Garantias do investigado',
          'Conclusão do inquérito',
          'Prisão e liberdade provisória',
          'Disposições constitucionais aplicáveis ao Processo Penal',
          'Lei nº 9.099/1995',
        ],
      },
      {
        nome: 'Direitos Humanos',
        tipo: 'rot',
        prioridade: 'media',
        conteudos: [
          'Teoria geral dos direitos humanos',
          'Conceitos e terminologia',
          'Estrutura normativa',
          'Fundamentação',
          'Afirmação histórica dos direitos humanos',
          'Direitos humanos e responsabilidade do Estado',
          'Direitos humanos na Constituição Federal',
          'Política Nacional de Direitos Humanos',
          'Tratados internacionais de direitos humanos',
        ],
      },
      {
        nome: 'Informática',
        tipo: 'base',
        prioridade: 'media',
        conteudos: [
          'Fundamentos de computação',
          'Organização e arquitetura de computadores',
          'Hardware e software',
          'Entrada, saída e armazenamento',
          'Sistemas operacionais',
          'Virtualização',
          'Redes de computadores',
          'Modelo OSI/ISO e TCP/IP',
          'Protocolos de rede',
          'VPN',
          'Computação em nuvem',
          'Vírus, worms e pragas virtuais',
          'Antivírus, firewall e anti-spyware',
          'Internet e intranet',
          'Navegadores',
          'Correio eletrônico',
          'Ferramentas de busca e redes sociais',
          'Acesso remoto e transferência de arquivos',
          'Windows 10',
          'GNU/Linux',
          'Android e iOS',
          'Microsoft Office e LibreOffice',
          'Mineração de dados',
          'Aprendizado de máquina',
          'Big Data',
          'Python e R',
          'API',
          'Metadados',
          'Teoria da informação',
          'Banco de dados',
          'Modelagem entidade-relacionamento',
          'Dados estruturados e não estruturados',
          'Banco de dados relacionais',
          'Chaves e relacionamentos',
        ],
      },
      {
        nome: 'Estatística',
        tipo: 'base',
        prioridade: 'media',
        conteudos: [
          'Estatística descritiva',
          'Gráficos, diagramas e tabelas',
          'Medidas de posição',
          'Medidas de dispersão',
          'Assimetria e curtose',
          'Probabilidade',
          'Probabilidade condicional e independência',
          'Variáveis aleatórias discretas e contínuas',
          'Distribuições de probabilidade',
          'Esperança e momentos',
          'Distribuições especiais',
          'Leis dos grandes números',
          'Teorema central do limite',
          'Amostras aleatórias',
          'Distribuições amostrais',
          'Inferência estatística',
          'Estimação pontual',
          'Estimação intervalar',
          'Testes de hipóteses',
          'Regressão linear',
          'Análise de variância',
          'Análise de resíduos',
          'Técnicas de amostragem',
          'Tamanho amostral',
        ],
      },
      {
        nome: 'Contabilidade',
        tipo: 'base',
        prioridade: 'alta',
        conteudos: [
          'Conceitos, objetivos e finalidades da contabilidade',
          'Patrimônio',
          'Equação fundamental do patrimônio',
          'Situação líquida',
          'Atos e fatos administrativos',
          'Contas',
          'Débito, crédito e saldo',
          'Plano de contas',
          'Escrituração',
          'Lançamentos contábeis',
          'Livros de escrituração',
          'Regime de competência e regime de caixa',
          'Operações contábeis diversas',
          'Balancete de verificação',
          'Balanço patrimonial',
          'Demonstração do resultado do exercício',
          'Lei nº 6.404/1976',
          'Pronunciamentos CPC',
          'NBC TSP Estrutura Conceitual',
        ],
      },
    ],
  },
  {
    id: 'camara-tecnico-legislativo-assistente-legis-adm',
    nome: 'Câmara dos Deputados - Técnico Legislativo – Assistente Legis. e Adm',
    materias: [
      {
        nome: 'Direito Constitucional',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Constituição Federal de 1988',
          'Poder constituinte',
          'Princípios Fundamentais',
          'Direitos e garantias fundamentais',
          'Organização do Estado',
          'Administração Pública na Constituição',
          'Poder Legislativo',
          'Regime jurídico-constitucional dos parlamentares',
          'Processo Legislativo',
          'Fiscalização contábil, financeira e orçamentária',
          'Defesa do Estado e das instituições democráticas',
        ],
      },
      {
        nome: 'Regimento Interno da Câmara dos Deputados',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Resolução nº 17/1989 — Câmara dos Deputados',
          'Disposições preliminares — arts. 1º a 13',
          'Órgãos da Câmara — arts. 14 a 22',
          'Sessões da Câmara — arts. 65 a 78',
          'Exercício do mandato — arts. 226 a 243',
        ],
      },
      {
        nome: 'Administração Geral',
        tipo: 'base',
        prioridade: 'alta',
        conteudos: [
          'Fundamentos da Administração',
          'Gestão de pessoas e comportamento organizacional',
          'Clima, cultura e liderança',
          'Desenvolvimento, treinamento e competências',
          'Recrutamento e seleção',
          'Gestão por resultados e trabalho híbrido',
          'Gestão patrimonial',
          'Governança, estratégia e planejamento estratégico',
          'Balanced Scorecard — BSC e indicadores',
          'Governança corporativa, controles e integridade',
          'Gestão de projetos',
          'Gestão de processos',
          'Hierarquia do processo',
        ],
      },
      {
        nome: 'Licitações e Contratos',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Lei nº 14.133/2021 e licitação pública',
          'Modalidades e contratação direta',
          'Contratos administrativos',
          'Planejamento e fiscalização contratual',
          'Execução contratual e irregularidades',
          'Penalidades e sanções administrativas',
          'Aspectos econômico-financeiros do contrato',
          'Alterações, prorrogações e ciclo de vida do contrato',
          'Riscos e responsabilidades contratuais',
          'Contratos de terceirização',
        ],
      },
      {
        nome: 'Tecnologia da Informação, Dados e Estatística',
        tipo: 'base',
        prioridade: 'alta',
        conteudos: [
          'Hardware e software',
          'Sistemas operacionais e Microsoft 365',
          'Redes, Internet e intranet',
          'Navegadores, comunicação e colaboração',
          'Computação em nuvem, acesso remoto e transferência de arquivos',
          'Segurança da informação e governança digital',
          'Inteligência artificial, prompts e ética digital',
          'Dados, análise de dados e governança da informação',
          'Big Data, dados estruturados e ETL',
          'Banco de dados e mineração de dados',
          'Estatística e probabilidade',
          'Visualização de dados',
        ],
      },
      {
        nome: 'Administração Orçamentária e Financeira',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Programação, execução e controle orçamentário-financeiro',
          'Execução da despesa pública',
          'GRU, sistemas e suprimento de fundos',
          'Restos a pagar e despesas de exercícios anteriores',
          'Retenção e recolhimento de tributos',
        ],
      },
      {
        nome: 'Língua Portuguesa',
        tipo: 'base',
        prioridade: 'alta',
        conteudos: [
          'Interpretação e compreensão de textos',
          'Tipos e gêneros textuais',
          'Ortografia oficial',
          'Coesão textual',
          'Classes de palavras e estrutura morfossintática',
          'Coordenação, subordinação e pontuação',
          'Concordância, regência e crase',
          'Colocação pronominal',
          'Reescrita de frases e parágrafos',
          'Semântica e significação das palavras',
        ],
      },
      {
        nome: 'Língua Inglesa',
        tipo: 'base',
        prioridade: 'media',
        conteudos: [
          'Compreensão de textos em inglês',
          'Vocabulário e estrutura da língua inglesa',
          'Gramática aplicada à interpretação',
          'Formas contemporâneas da linguagem inglesa',
        ],
      },
      {
        nome: 'Raciocínio Lógico e Analítico',
        tipo: 'base',
        prioridade: 'alta',
        conteudos: [
          'Lógica proposicional',
          'Estruturas lógicas e dedução',
          'Raciocínio verbal, matemático e sequencial',
          'Reconhecimento de padrões e orientação espacial/temporal',
          'Gráficos e tabelas',
          'Problemas de lógica e raciocínio',
          'Falácias',
          'Noções de estatística',
        ],
      },
      {
        nome: 'Direito Administrativo',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Organização administrativa',
          'Atos administrativos',
          'Agentes públicos e servidores públicos',
          'Regime jurídico dos servidores públicos federais',
          'Poderes administrativos',
          'Controle da administração pública',
          'Responsabilidade civil do Estado',
          'Improbidade Administrativa',
          'Lei de Acesso à Informação',
          'Lei Geral de Proteção de Dados',
          'Processo Administrativo Federal',
        ],
      },
      {
        nome: 'Administração Pública',
        tipo: 'rot',
        prioridade: 'alta',
        conteudos: [
          'Evolução da Administração Pública',
          'Transparência, controle social e accountability',
          'Excelência nos serviços públicos',
          'Comunicação e redes organizacionais',
          'Governança pública',
          'Intermediação de interesses',
          'Políticas públicas',
          'Políticas públicas no Estado brasileiro contemporâneo',
          'Corrupção e políticas públicas',
          'Reformas administrativas e papel do Estado',
          'Mudanças institucionais e novos arranjos administrativos',
        ],
      },
    ],
  },
]
